
server:
  port: 8099
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  main:
    allow-circular-references: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: test-alticci-sequence
  datasource:
    url: jdbc:h2:mem:alticci-ms
    driver-class-name: org.h2.Driver
    username: admin
    passorwd: root123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    web: info
    sql: info
    root: info
    org:
      springframework:
        security: DEBUG

jwt:
  expiration: 3600000
  secret: secretExemploToken